/*
 * JBILLING CONFIDENTIAL
 * _____________________
 *
 * [2003] - [2012] Enterprise jBilling Software Ltd.
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Enterprise jBilling Software.
 * The intellectual and technical concepts contained
 * herein are proprietary to Enterprise jBilling Software
 * and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden.
 */

package com.sapienter.jbilling.server.provisioning.task.mmsc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.1
 * Thu May 28 10:10:49 EST 2009
 * Generated source version: 2.2.1
 * 
 */

@WebFault(name = "Exception", targetNamespace = "http://mmschandlerfacade.efs.teliasonera.se/")
public class MMSCException_Exception extends Exception {
    public static final long serialVersionUID = 20090528101049L;
    
    private com.sapienter.jbilling.server.provisioning.task.mmsc.MMSCException exception;

    public MMSCException_Exception() {
        super();
    }
    
    public MMSCException_Exception(String message) {
        super(message);
    }
    
    public MMSCException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MMSCException_Exception(String message, com.sapienter.jbilling.server.provisioning.task.mmsc.MMSCException exception) {
        super(message);
        this.exception = exception;
    }

    public MMSCException_Exception(String message, com.sapienter.jbilling.server.provisioning.task.mmsc.MMSCException exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.sapienter.jbilling.server.provisioning.task.mmsc.MMSCException getFaultInfo() {
        return this.exception;
    }
}
